### ISSUE TITLE
Cannot launch Ray Autoscaler when running ray example

### ISSUE THREAD

**Issue by miguelvr** [facebookresearch/ClassyVision#330]
## ❓ Questions and Help

Hi, I'm trying to train a model with classy vision following the ray distributed example, but I'm not managing to launch the cluster properly (or at least I think this is the case)

Everything works, including the `ray start cluster_config.yml` command.

However, when I `tail` the ray logs, I'm getting a recurrent error:
```
2019-12-31 14:30:47,828	ERROR node_provider.py:302 -- create_instances: Max attempts (5) exceeded.
2019-12-31 14:30:47,828	ERROR autoscaler.py:349 -- Launch failed
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 347, in run
    self._launch_node(config, count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 337, in _launch_node
    }, count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/aws/node_provider.py", line 230, in create_node
    self._create_node(node_config, tags, count)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/aws/node_provider.py", line 303, in _create_node
    raise exc
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/autoscaler/aws/node_provider.py", line 290, in _create_node
    created = self.ec2_fail_fast.create_instances(**conf)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/botocore/client.py", line 622, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 4 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.
```

Do I really need to contact Amazon to extend my service limits to run distributed training with classy vision and ray?

Thanks,
Miguel

**Comment by miguelvr** [comment]
solved by asking AWS support to increase my vCPU limit for P-type instances

**Comment by mannatsingh** [comment]
@miguelvr glad that you were able to resolve the issue by increasing your vCPU limit. 

Just an FYI, If you look at https://github.com/facebookresearch/ClassyVision/blob/master/examples/ray/cluster_config.yml, it requests for 2 workers by default. You can also reduce the number of workers to 1 to reduce the total vCPU capacity utilized by your job.
