### ISSUE TITLE
ValueError: bad value(s) in fds_to_keep？

### ISSUE THREAD

**Issue by luolugithub** [facebookresearch/ClassyVision#673]
## ❓ Questions and Help
how to handle ？

**Comment by luolugithub** [comment]
INFO:root:Number of activations in model: 65329152
Traceback (most recent call last):
  File "./classy_train.py", line 190, in <module>
    main(args, config)
  File "./classy_train.py", line 112, in main
    trainer.train(task)
  File "/home/xkjs2/PycharmProjects/ClassyVision/classy_vision/trainer/local_trainer.py", line 26, in train
    super().train(task)
  File "/home/xkjs2/PycharmProjects/ClassyVision/classy_vision/trainer/classy_trainer.py", line 43, in train
    task.on_phase_start()
  File "/home/xkjs2/PycharmProjects/ClassyVision/classy_vision/tasks/classification_task.py", line 1190, in on_phase_start
    self.advance_phase()
  File "/home/xkjs2/PycharmProjects/ClassyVision/classy_vision/tasks/classification_task.py", line 1136, in advance_phase
    self.create_data_iterators()
  File "/home/xkjs2/PycharmProjects/ClassyVision/classy_vision/tasks/classification_task.py", line 1149, in create_data_iterators
    self.data_iterator = iter(self.dataloader)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/xkjs2/anaconda3/envs/ClassyVision/lib/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep

**Comment by mannatsingh** [comment]
Hi @luolugithub can you go over the thread in https://github.com/facebookresearch/ClassyVision/issues/597 and try the suggestions there and let me know?

**Comment by luolugithub** [comment]
@mannatsingh 
Got it, thank you very much！！！
