### ISSUE TITLE
Could you please provide a config for training efficientnet？

### ISSUE THREAD

**Issue by shinianzhihou** [facebookresearch/ClassyVision#680]
Could you please provide a config for training efficientnet？

I am confusing about the config for efficientnet.

**Comment by shinianzhihou** [comment]
config(model):
    "model": {
        "name": "efficientnet_b0",
        "bn_momentum": 0.01,
        "bn_epsilon": 1e-3,
        "drop_connect_rate": 0.0,
        "num_classes": 15,
        "width_divisor": 8,
        "min_width": null,
        "use_se": true,
        "heads": [
          {
            "name": "fully_connected",
            "unique_id": "default_head",
            "num_classes": 15,
            "fork_block": "block3-2",
            "in_plane": 2048
          }
        ]
    },

Traceback (most recent call last):
  File "classy_train.py", line 190, in <module>
    main(args, config)
  File "classy_train.py", line 112, in main
    trainer.train(task)
  File "/home/shinian/ClassyVision/classy_vision/trainer/distributed_trainer.py", line 82, in train
    super().train(task)
  File "/home/shinian/ClassyVision/classy_vision/trainer/classy_trainer.py", line 46, in train
    task.step()
  File "/home/shinian/ClassyVision/classy_vision/tasks/classy_task.py", line 163, in step
    self.train_step()
  File "/home/shinian/ClassyVision/classy_vision/tasks/classification_task.py", line 1017, in train_step
    output = self.model(sample["input"])
  File "/home/shinian/ClassyVision/classy_vision/models/classy_model.py", line 97, in __call__
    return self.forward(*args, **kwargs)
  File "/home/shinian/ClassyVision/classy_vision/models/classy_model.py", line 111, in forward
    out = self.classy_model(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shinian/ClassyVision/classy_vision/models/efficientnet.py", line 536, in forward
    outputs = block(outputs, drop_connect_rate=drop_connect_rate)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'drop_connect_rate'
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/rapids/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)

**Comment by shinianzhihou** [comment]
where can i find the pretrained model （.pt） for efficientnet?
